export interface Hack {
  award: string;
  awardTone: "amber" | "cyan";
  title: string;
  desc: string;
  chips: string[];
  href: string;
  internal?: boolean;
  img?: string;
  imgAlt?: string;
}

export const hacks: Hack[] = [
  {
    award: "WinHacks 2026 — Finalist",
    awardTone: "amber",
    title: "SketchBot",
    desc: "Design in pixels, then a robot draws it on paper for real. Camera-vision positioning, ESP32 motor control, Next.js + WebSockets, Gemini-generated designs.",
    chips: ["ESP32", "Camera Vision", "Next.js"],
    href: "/projects/sketchbot",
    internal: true,
    img: "/img/sketchbot-a.jpg",
    imgAlt: "SketchBot drawing robot with marker attachment",
  },
  {
    award: "Hack the 6ix 2026 — Solo Build",
    awardTone: "cyan",
    title: "Edge Pong",
    desc: "Projected ping-pong with an edge-AI-tracked smart paddle — feel each impact through four-quadrant spatial haptics, all processed on-device.",
    chips: ["ESP32-C5", "Haptics", "Three.js"],
    href: "/projects/edge-pong",
    internal: true,
  },
  {
    award: "WinHacks 2025 — 2nd Overall · 1st in Category",
    awardTone: "amber",
    title: "PresentPro",
    desc: "Real-time presentation coaching: live speech analysis flags pacing over 160 wpm and nudges you through a vibrating IoT wearable. React, FastAPI, AssemblyAI, ESP32.",
    chips: ["AssemblyAI", "FastAPI", "ESP32"],
    href: "/projects/presentpro",
    internal: true,
    img: "/img/presentpro-a.jpg",
    imgAlt: "PresentPro IoT wrist wearable with ESP32 and haptic feedback",
  },
  {
    award: "WinHacks 2024 — 2nd Place Overall",
    awardTone: "amber",
    title: "Second Life",
    desc: "Give your EV battery a second life in a microgrid — a platform to collect, test, and repurpose end-of-life EV batteries for energy storage. Born from my battery research.",
    chips: ["Next.js", "Prisma", "Energy"],
    href: "/projects/second-life",
    internal: true,
    img: "/img/secondlife-award.jpg",
    imgAlt: "Second Life team receiving 2nd place overall at WinHacks 2024",
  },
  {
    award: "NASA Space Apps 2025 — 1st Place + Global Nomination",
    awardTone: "amber",
    title: "Meteor Madness",
    desc: "NASA Space Apps Challenge: visualizing near-Earth asteroid data to make planetary defense tangible. Won Windsor and earned a global nomination.",
    chips: ["NASA Data", "JavaScript", "Visualization"],
    href: "/projects/meteor-madness",
    internal: true,
    img: "/img/nasa-space-apps-1.jpg",
    imgAlt: "Team holding 1st Place Windsor certificates at the NASA Space Apps Challenge",
  },
  {
    award: "ClubHacks 2026 — Finalist",
    awardTone: "amber",
    title: "SketchBot V2",
    desc: "The drawing robot, rebuilt: AprilTag fiducial tracking for precise camera-vision positioning, 18650 power, and a cleaner chassis.",
    chips: ["AprilTags", "ESP32", "Camera Vision"],
    href: "/projects/sketchbot",
    internal: true,
    img: "/img/clubhacks-sketchbot-v2-1.jpg",
    imgAlt: "SketchBot V2 with AprilTag marker and 18650 battery power",
  },
  {
    award: "BorderHacks 2021 — People's Choice + Open Data Winner",
    awardTone: "amber",
    title: "WinParks",
    desc: "Mobile app helping people explore the trails, parks, and heritage parks of Windsor.",
    chips: ["Mobile", "Maps"],
    href: "/projects/winparks",
    internal: true,
    img: "/img/winparks-a.jpg",
    imgAlt: "WinParks mobile app showing Windsor park listings",
  },
  {
    award: "UWindsor Automotive UI/UX Challenge 2026 — 1st Place",
    awardTone: "amber",
    title: "RV Interface Challenge",
    desc: "Winning entry in the automotive UI/UX challenge — designing and building a recreational-vehicle interface in C#.",
    chips: ["C#", "UI/UX", "Automotive"],
    href: "/projects/rv-challenge",
    internal: true,
    imgAlt: "RV interface challenge entry",
  },
  {
    award: "WinHacks 2022",
    awardTone: "cyan",
    title: "WinGrid",
    desc: "Keeping all the electric vehicles on the grid — managing EV charging load at scale.",
    chips: ["EV", "Grid"],
    href: "/projects/wingrid",
    internal: true,
    img: "/img/wingrid-a.jpg",
    imgAlt: "WinGRID mobile app for planning EV charger installations",
  },
  {
    award: "Hack the Northeast 2020",
    awardTone: "cyan",
    title: "Covid-19 Global",
    desc: "Desktop application providing trustworthy Covid-19 statistics from countries around the world.",
    chips: ["Desktop", "Data"],
    href: "/projects/covid-19-global",
    internal: true,
    img: "/img/covid-a.png",
    imgAlt: "Covid-19 Global desktop app showing worldwide statistics",
  },
  {
    award: "Bordercity Hackathon 2017 — 1st Place",
    awardTone: "amber",
    title: "WeatherPy",
    desc: "First hackathon, first win — a Python weather app that started a decade of building under pressure.",
    chips: ["Python"],
    href: "/projects/weatherpy",
    internal: true,
  },
  {
    award: "MasseyHacks 2018",
    awardTone: "cyan",
    title: "Hand-Motion Zombie FPS",
    desc: "A first-person zombie shooter controlled entirely by hand motion.",
    chips: ["Game Dev", "Motion Control"],
    href: "/projects/zombie-fps",
    internal: true,
  },
  {
    award: "Bordercity Hackathon 2018",
    awardTone: "cyan",
    title: "Virtual Connect 4",
    desc: "A virtual Connect 4 app built in a weekend.",
    chips: ["Game Dev"],
    href: "/projects/connect4",
    internal: true,
  },
  {
    award: "BorderHacks 2020 — Solo",
    awardTone: "cyan",
    title: "Exponent Base e Calculator",
    desc: "Numerical methods under time pressure: e^x to any required number of correct significant digits.",
    chips: ["Python", "Numerical Methods"],
    href: "/projects/exponent-calculator",
    internal: true,
  },
  {
    award: "Hackathon Project — 2024",
    awardTone: "cyan",
    title: "EcoRoute",
    desc: "Route optimization with an environmental lens.",
    chips: ["TypeScript"],
    href: "/projects/ecoroute",
    internal: true,
  },
  {
    award: "Hackathon Project — 2024",
    awardTone: "cyan",
    title: "wordConquer",
    desc: "A word game built fast.",
    chips: ["TypeScript"],
    href: "/projects/wordconquer",
    internal: true,
  },
  {
    award: "Engineering Competitions",
    awardTone: "amber",
    title: "WEC · OEC",
    desc: "Four straight 1st places in WEC programming (2020–2023) and four Ontario Engineering Competition appearances — see the full record.",
    chips: ["Competitive Programming"],
    href: "/competitions",
    internal: true,
    img: "/img/wec-1st-place.jpg",
    imgAlt: "1st place in programming at the Windsor Engineering Competition",
  },
];

/** The spread shown on the homepage — podium finishes and crowd favourites. */
export const featuredHackTitles = [
  "Meteor Madness",
  "PresentPro",
  "Second Life",
  "SketchBot",
  "WeatherPy",
  "Edge Pong",
];
